USE [master]
GO
/****** Object: Database [CUENTASDB] Script Date: 04/10/2022 11:30:58
******/
CREATE DATABASE [CUENTASDB]
go
USE [CUENTASDB]
GO
/****** Object: Table [dbo].[CUENTAS] Script Date: 04/10/2022 11:30:59
******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON

GO
CREATE TABLE [dbo].[CUENTAS](
 [IDCUENTA] [nvarchar](12) NOT NULL,
 [SALDO] [money] NULL,
CONSTRAINT [PK_CUENTAS] PRIMARY KEY CLUSTERED
(
 [IDCUENTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object: Table [dbo].[MOVIMIENTOS] Script Date: 04/10/2022 11:30:59
******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MOVIMIENTOS](
 [IDMOVIMIENTO] [int] IDENTITY(1,1) NOT NULL,
 [IDCUENTA] [nvarchar](12) NULL,
 [SALDO_ANTERIOR] [money] NULL,
 [SALDO_POSTERIOR] [money] NULL,
 [IMPORTE] [money] NULL,
 [FXMOVIMIENTO] [datetime] NULL,
CONSTRAINT [PK_MOVIMIENTOS] PRIMARY KEY CLUSTERED
(
 [IDMOVIMIENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[CUENTAS] ([IDCUENTA], [SALDO]) VALUES (N'200700000001', 0.0000)
INSERT [dbo].[CUENTAS] ([IDCUENTA], [SALDO]) VALUES (N'200700000002', 0.0000)
GO
SET IDENTITY_INSERT [dbo].[MOVIMIENTOS] ON
INSERT [dbo].[MOVIMIENTOS] ([IDMOVIMIENTO], [IDCUENTA], [SALDO_ANTERIOR],
[SALDO_POSTERIOR], [IMPORTE], [FXMOVIMIENTO]) VALUES (1, N'200700000001',
50.0000, 0.0000, 50.0000, CAST(N'2022-10-03T15:49:17.170' AS DateTime))
INSERT [dbo].[MOVIMIENTOS] ([IDMOVIMIENTO], [IDCUENTA], [SALDO_ANTERIOR],
[SALDO_POSTERIOR], [IMPORTE], [FXMOVIMIENTO]) VALUES (2, N'200700000002',
0.0000, 50.0000, 50.0000, CAST(N'2022-10-03T15:49:17.173' AS DateTime))
SET IDENTITY_INSERT [dbo].[MOVIMIENTOS] OFF
GO
ALTER TABLE [dbo].[CUENTAS] ADD CONSTRAINT [DF_CUENTAS_SALDO] DEFAULT ((0))
FOR [SALDO]
GO
ALTER TABLE [dbo].[CUENTAS] WITH CHECK ADD CONSTRAINT [CK_CUENTAS] CHECK
(([SALDO]>=(0)))
GO
ALTER TABLE [dbo].[CUENTAS] CHECK CONSTRAINT [CK_CUENTAS]
GO
GO 
